version: '3.9'
services:
  webserver:
    build: ./.docker/server_http/
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    ports:
      - ${PORT}:80
    restart: always
    labels:
      ho.ctf.cyrhades: "1"