version: '3.3'
services:
  webserver:
    build: http/
    ports:
      - "80:80"
    image: node_lfi
    labels:
      ho.ctf.cyrhades: webserver
    container_name: ho-webserver
    command: npm start